# Hibernate ORM & Dev Services
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.hibernate-orm.log.sql=true

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=quarkus
quarkus.datasource.password=quarkus_password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/fermentcraft_db

# REST Client Reactive - Servicio externo simulado
quarkus.rest-client.shipping-service.url=https://mock.example.com
#quarkus.rest-client.shipping-service.scope=jakarta.enterprise.context.ApplicationScoped

# Kafka Messaging (Despacho de Cajas)
mp.messaging.outgoing.box-dispatched.connector=smallrye-kafka
mp.messaging.outgoing.box-dispatched.topic=box-dispatched
mp.messaging.outgoing.box-dispatched.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# Reactivamos Dev Services para Kafka (Quarkus levantará Redpanda automáticamente si Docker está activo)
quarkus.kafka.devservices.enabled=false
kafka.bootstrap.servers=localhost:19092